/// Flutter icons MyIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyIcons
///      fonts:
///       - asset: fonts/MyIcons.ttf
///       - asset: fonts/IconSet.ttf
///
///
/// * Linecons, Copyright (C) 2013 by Designmodo
///         Author:    Designmodo for Smashing Magazine
///         License:   CC BY ()
///         Homepage:  http://designmodo.com/linecons-free/
/// * Web Symbols, Copyright (c) 2011 by Just Be Nice studio. All rights reserved.
///         Author:    Just Be Nice studio
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.justbenicestudio.com/
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class MyIcons {
  MyIcons._();

  static const _kFontFam = 'MyIcons';
  static const _kFontPkg = null;

  static const IconData calendar =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ok_circle =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user =
      IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checkmark_cicle =
      IconData(0xe87f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_1 =
      IconData(0xf007, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_circle =
      IconData(0xf058, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tasks =
      IconData(0xf0ae, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData graduation_cap =
      IconData(0xf19d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData binoculars =
      IconData(0xf1e5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clipboard_list =
      IconData(0xf46d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_graduate =
      IconData(0xf501, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_tie =
      IconData(0xf508, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_contract =
      IconData(0xf56c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_invoice =
      IconData(0xf570, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_invoice_dollar =
      IconData(0xf571, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_signature =
      IconData(0xf573, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fingerprint =
      IconData(0xf577, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}

class IconSet {
  IconSet._();

  static const _kFontFam = 'Iconset';
  static const _kFontPkg = null;
  static const IconData iconCategory =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconSubCat =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconBudget =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData IconFour =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData IconFive =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData IconSix =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconAbsentCount =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconPresentCount =
      IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconTicket =
      IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconTaskCount =
      IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}

class AppAssets {

  static const String logo = 'assets/images/logo.png';
  static const String locationBackground = 'assets/images/bg_location.png';
  static const String background = 'assets/images/background.png';

  static const String photographerIcon = 'assets/images/photographer_icon.png';
  static const String pickUpIcon = 'assets/images/pickup_icon.png';
  static const String loc = 'assets/images/loc.png';
  static const String location = 'assets/images/location.png';
  static const String loginBg = 'assets/images/login.png';




  //on board asset
  static const String onBoardBG = 'assets/images/onBoard/bg_onboard.png';
  static const String imageBG = 'assets/images/onBoard/image_bg.png';
  static const String imageB1 = 'assets/images/onBoard/image_b1.png';
  static const String imageB2 = 'assets/images/onBoard/image_b2.png';
  static const String imageB3 = 'assets/images/onBoard/image_b3.png';

  static const String loginDashBoard = 'assets/images/login_logo.png';
  static const String loginDashBoardBG = 'assets/images/login_bg.png';



  static const String homeBackground = 'assets/images/home_bg.png';
  static const String locationBackground1 = 'assets/images/bg_1.png';
  static const String title_1 = 'assets/images/title_1.png';
  static const String locationIcon = 'assets/images/location_icon.png';
  static const String otpBackground = 'assets/images/otp.png';
  static const String loginTop = 'assets/images/login_top.png';
  static const String bgPhotoGallery = 'assets/images/bg_photo_gallery.png';
  static const String paymentSuccessIcon = 'assets/images/payment_success_icon.png';
  static const String bgPaymentSuccess = 'assets/images/bg_payment_success.png';
  static const String bgPaymentSuccessNew = 'assets/images/bg_payment_success_new.png';
  static const String paymentSuccessParty =
      'assets/images/payment_success_party.png';
  static const String bgEditProfile = 'assets/images/bg_edit_profile.png';

  static const String bgprofile1 = 'assets/images/profile1.png';
  static const String bgprofile2 = 'assets/images/profile2.png';
  static const String bgprofile3 = 'assets/images/profile3.png';

  static const String sharePhotos = 'assets/images/galleryShare.png';

  static const String bgIntroStep1 = 'assets/images/step1.png';
  static const String bgIntroStep2 = 'assets/images/step2.png';
  static const String bgIntroStep3 = 'assets/images/step3.png';

  static const String mapIcon = 'assets/images/map_icon.png';
  static const String galleyPNG = 'assets/images/galley.png';
  static const String circleIcon = 'assets/images/circle_icon.png';
  static const String portfolioBg = 'assets/images/portfolio_bg.png';
  static const String cameraHomeIcon = 'assets/images/camera_home_icon.png';
  static const String editProfileIcon = 'assets/images/edit_profile_icon.png';


  // SVG Icons (if any)
  static const String _svgPath = 'assets/svg/';

  // Person Icon
  static const String personIcon = 'assets/svg/person_icon.svg';
  static const String googleIcon = 'assets/svg/google_icon.svg';
  static const String facebookIcon = 'assets/svg/facebook_icon.svg';
  static const String effOffIcon = 'assets/svg/eye-off.svg';
  static const String posLogoIcon = 'assets/svg/pos_logo.svg';

  static const String tickCircle = 'assets/svg/tick_circle.svg';

  static const String infoCircle = 'assets/svg/info_circle.svg';
  static const String share = 'assets/svg/share.svg';
  static const String galley = 'assets/svg/gallery.svg';

  static const String mapIcons = 'assets/svg/mapIcon.svg';

  static const String icSandTimer = 'assets/images/ic_sand_timer.png';

  static const String doubleTick = 'assets/images/double_tick.png';



  static const String mobileIcons = 'assets/svg/mobile_icon.svg';
  static const String chatIcons = 'assets/svg/chat_icon.svg';
  static const String menuIcons = 'assets/svg/menu_icon.svg';

  static const String tickIcon = 'assets/svg/tick_icon.svg';
  static const String singleTickIcon = 'assets/svg/single_tick.svg';
  static const String deleteIcon = 'assets/svg/delete_icon.svg';
  static const String photoIcon = 'assets/svg/photo_icon.svg';
  static const String moveImageIcon = 'assets/svg/move_image_icon.svg';
  static const String deletedIcon = 'assets/svg/deleted_icon.svg';

  //menu icon
  static const String mainMenuIcon = 'assets/svg/menu/main_menu.svg';
  static const String manageIcon = 'assets/svg/menu/manage_icon.svg';
  static const String operationIcon = 'assets/svg/menu/operation_icon.svg';
  static const String adminIcon = 'assets/svg/menu/admin_icon.svg';
  static const String authIcon = 'assets/svg/menu/auth_icon.svg';
  static const String settingsIcon = 'assets/svg/menu/settings_icon.svg';
  static const String notifyAlertIcon = 'assets/svg/menu/notify_alert.svg';
  static const String notificationIcon = 'assets/svg/menu/notification_icon.svg';
  static const String reportIcon = 'assets/svg/menu/report_icon.svg';
  static const String brightnessIcon = 'assets/svg/menu/brightness_icon.svg';
  static const String searchIcon = 'assets/svg/menu/search_icon.svg';
  static const String upgradeIcon = 'assets/svg/menu/upgrade_icon.svg';
  static const String syncIcon = 'assets/svg/menu/sync_icon.svg';




  static const String icCamera = 'assets/images/ic_camera.png';
  static const String icMyLocation = 'assets/images/ic_my_location.png';


  static const String logoBG = 'assets/images/logo_bg.png';
  static const String centerBG = 'assets/images/center_bg.png';


  static const String viewGallery = 'assets/images/view_gallery.png';
  static const String tickIconTwo = 'assets/images/tick_icon_two.png';
  static const String loaderIcon = 'assets/images/loader_icon.png';
  static const String filesIcon = 'assets/images/files_icon.png';
  static const String portfolioMainBg = 'assets/images/portfolio_main_bg.png';


  // Animations
  static const String blastAnimation = 'assets/animations/blast.json';
  static const String blast2Animation = 'assets/animations/blast 2.json';
  static const String errorAnimation = 'assets/animations/error.json';
  static const String loadingAnimation = 'assets/animations/loading.json';



  // Fonts
  static const String fontFamily = 'Poppins';
}